# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "RelativeStateCommandCfg",
    "RelativeStateCommand",
    "terrain_spawn_goal_pair_success_rate_levels",
    "terrain_spawn_goal_pair_success_rate_levels_old",
    "skip_reward_term",
    "stricten_success_term",
    "activate_reward_term",
    "time_left",
    "task_reward",
    "heading_tracking",
    "exploration_reward",
    "forward_direction_reward",
    "mechanical_power",
    "command_success",
    "position_tracking",
    "rotation_tracking",
    "lin_vel_tracking",
    "ang_vel_tracking",
    "speeding",
    "incoming_wrench",
    "stall_penalty",
    "illegal_contact_penalty",
    "feet_lin_acc_l2",
    "feet_rot_acc_l2",
    "stand_penalty",
    "foot_touchdown_impact",
    "GaitReward",
    "forward_velocity",
    "air_time_reward",
    "air_time_variance_penalty",
    "foot_slip_penalty",
    "joint_position_penalty",
    "success",
    "success_terminate",
    "abnormal_robot_state",
    "speed_terminate",
    "log",
    "mean_mech_energy_per_joint",
    "total_average_mech_energy_per_joint",
    "mean_per_body_shock",
    "total_body_shock",
    "forwardness",
    "DefaultJointPositionStaticActionCfg",
    "DefaultJointPositionStaticAction",
]

from .commands import RelativeStateCommandCfg, RelativeStateCommand
from .curriculums import (
    terrain_spawn_goal_pair_success_rate_levels,
    terrain_spawn_goal_pair_success_rate_levels_old,
    skip_reward_term,
    stricten_success_term,
    activate_reward_term,
)
from .observations import time_left
from .rewards import (
    task_reward,
    heading_tracking,
    exploration_reward,
    forward_direction_reward,
    mechanical_power,
    command_success,
    position_tracking,
    rotation_tracking,
    lin_vel_tracking,
    ang_vel_tracking,
    speeding,
    incoming_wrench,
    stall_penalty,
    illegal_contact_penalty,
    feet_lin_acc_l2,
    feet_rot_acc_l2,
    stand_penalty,
    foot_touchdown_impact,
    GaitReward,
    forward_velocity,
    air_time_reward,
    air_time_variance_penalty,
    foot_slip_penalty,
    joint_position_penalty,
)
from .terminations import (
    success,
    success_terminate,
    abnormal_robot_state,
    speed_terminate,
    log,
    mean_mech_energy_per_joint,
    total_average_mech_energy_per_joint,
    mean_per_body_shock,
    total_body_shock,
    forwardness,
)
from .actions import DefaultJointPositionStaticActionCfg, DefaultJointPositionStaticAction
from isaaclab.envs.mdp import *
