# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Bake ``mw_ranges.json`` into a static Python module ``mw_ranges_baked.py``.

Run with the IsaacLab venv (no IsaacLab imports needed)::

    ./isaaclab.sh -p source/.../utils/parity/bake_ranges.py

The output module exposes ``MW_RANGES: dict[str, dict[str, tuple]]`` keyed by
the MW task name (``drawer-open-v3``).
"""

from __future__ import annotations

import json
from pathlib import Path

_HERE = Path(__file__).parent
_IN = _HERE / "mw_ranges.json"
_OUT = _HERE / "mw_ranges_baked.py"


def _t(values: list[float]) -> str:
    return f"({values[0]:.6g}, {values[1]:.6g}, {values[2]:.6g})"


def main() -> None:
    raw = json.loads(_IN.read_text())
    lines: list[str] = []
    lines.append("# Copyright (c) 2022-2026, The Isaac Lab Project Developers.")
    lines.append("# All rights reserved.  SPDX-License-Identifier: BSD-3-Clause")
    lines.append("# AUTO-GENERATED by ``utils/parity/bake_ranges.py``. Do not hand-edit.")
    lines.append('"""MW per-task (obj_init, target) sampling ranges, from the v3 MT50 dump."""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("MW_RANGES: dict[str, dict[str, tuple[float, float, float]]] = {")
    for task in sorted(raw.keys()):
        r = raw[task]
        lines.append(f"    {task!r}: {{")
        lines.append(f"        'obj_low': {_t(r['obj_init_min'])},")
        lines.append(f"        'obj_high': {_t(r['obj_init_max'])},")
        lines.append(f"        'goal_low': {_t(r['target_min'])},")
        lines.append(f"        'goal_high': {_t(r['target_max'])},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("__all__ = ['MW_RANGES']")
    lines.append("")
    _OUT.write_text("\n".join(lines))
    print(f"[bake] wrote {_OUT} ({len(raw)} tasks)")


if __name__ == "__main__":
    main()
